### ISSUE TITLE
请问Ctypes能在游戏内模拟么？

### ISSUE THREAD

**Issue by icoreman** [bode135/VirtualKey_with_Ctypes#1]
我用什么pynput、win32api只能在普通程序模拟，没问题，游戏内不行，Ctypes是驱动模拟，能否在游戏中使用？当然，只是前台模拟，不做后台模拟

**Comment by bode135** [comment]
驱动模拟适用于D3D游戏。
我在LOL里面没问题。
（不过没有任何一种方法能打包票的，因为对方也可以做针对性的反作弊手段，例如检测异常的dll。）
反正一句话：不行就换。

**Comment by limerencewithcode** [comment]
你好，能在lol里面使用吗，如果可以的话怎么做呢，要编译出exe还是怎么样呢，我用不好使啊

**Comment by bode135** [comment]
Ctypes可以用, 但得自己调节驱动模拟的参数...
前阵子我设置的被LOL屏蔽了.
更新部分参数后能再次使用...
参考这里的ctypes代码: https://github.com/bode135/pydamo/issues/6

**Comment by bode135** [comment]
```
from ctypes import POINTER, c_ulong, Structure, c_ushort, c_short, c_long, byref, windll, pointer, sizeof, Union
from bd_time import tt, vk

PUL = POINTER(c_ulong)


class KeyBdInput(Structure):
    _fields_ = [("wVk", c_ushort),
                ("wScan", c_ushort),
                ("dwFlags", c_ulong),
                ("time", c_ulong),
                ("dwExtraInfo", PUL)]


class HardwareInput(Structure):
    _fields_ = [("uMsg", c_ulong),
                ("wParamL", c_short),
                ("wParamH", c_ushort)]


class MouseInput(Structure):
    _fields_ = [("dx", c_long),
                ("dy", c_long),
                ("mouseData", c_ulong),
                ("dwFlags", c_ulong),
                ("time", c_ulong),
                ("dwExtraInfo", PUL)]


class Input_I(Union):
    _fields_ = [("ki", KeyBdInput),
                ("mi", MouseInput),
                ("hi", HardwareInput)]


class Input(Structure):
    _fields_ = [("type", c_ulong),
                ("ii", Input_I)]


class POINT(Structure):
    _fields_ = [("x", c_ulong),
                ("y", c_ulong)]


def get_mpos():
    orig = POINT()
    windll.user32.GetCursorPos(byref(orig))
    return int(orig.x), int(orig.y)


def set_mpos(pos):
    x, y = pos
    windll.user32.SetCursorPos(x, y)


MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004

MOUSEEVENTF_RIGHTDOWN = 0x00008
MOUSEEVENTF_RIGHTUP = 0x0010


def move_click(pos, move_back=False):
    origx, origy = get_mpos()
    set_mpos(pos)
    FInputs = Input * 2
    extra = c_ulong(0)
    ii_ = Input_I()
    ii_.mi = MouseInput(0, 0, 0, 2, 0, pointer(extra))

    tt.sleep(0.1)

    ii2_ = Input_I()
    ii2_.mi = MouseInput(0, 0, 0, 4, 0, pointer(extra))
    x = FInputs((0, ii_), (0, ii2_))
    windll.user32.SendInput(2, pointer(x), sizeof(x[0]))
    if move_back:
        set_mpos((origx, origy))
        return origx, origy

def move_right_click(pos, move_back=False):
    origx, origy = get_mpos()
    set_mpos(pos)
    FInputs = Input * 2
    extra = c_ulong(0)
    ii_ = Input_I()
    ii_.mi = MouseInput(0, 0, 0, MOUSEEVENTF_RIGHTDOWN, 0, pointer(extra))

    tt.sleep(0.1)

    ii2_ = Input_I()
    ii2_.mi = MouseInput(0, 0, 0, MOUSEEVENTF_RIGHTUP, 0, pointer(extra))
    x = FInputs((0, ii_), (0, ii2_))
    windll.user32.SendInput(2, pointer(x), sizeof(x[0]))
    if move_back:
        set_mpos((origx, origy))
        return origx, origy

def sendkey(scancode, pressed):
    FInputs = Input * 1
    extra = c_ulong(0)
    ii_ = Input_I()
    flag = 0x8
    ii_.ki = KeyBdInput(0, 0, flag, 0, pointer(extra))
    InputBox = FInputs((1, ii_))
    if scancode is None:
        return
    InputBox[0].ii.ki.wScan = scancode
    InputBox[0].ii.ki.dwFlags = 0x8

    if not (pressed):
        InputBox[0].ii.ki.dwFlags |= 0x2

    windll.user32.SendInput(1, pointer(InputBox), sizeof(InputBox[0]))

if __name__ == '__main__':

    tt.sleep(1)
    move_click(get_mpos())
    tt.sleep(1)
    move_right_click(get_mpos())

    def hex_to_dec(int_hex):
        if(isinstance(int_hex, (int, float))):
            int_hex = str(int_hex)
        int_dec = int(int_hex, 16)
        return int_dec

    class ScanCode:
        q = hex_to_dec(10)
        w = hex_to_dec(11)
        e = hex_to_dec(12)
        r = hex_to_dec(13)
        pass
    sc = ScanCode()

    tt.sleep(1)
    sendkey(scancode=sc.e, pressed=1)
```
[`键盘扫描码ScanCode参考`](https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html)
[`鼠标参考`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput)

**Comment by miqt** [comment]
> ```
> from ctypes import POINTER, c_ulong, Structure, c_ushort, c_short, c_long, byref, windll, pointer, sizeof, Union
> from bd_time import tt, vk
> 
> PUL = POINTER(c_ulong)
> 
> 
> class KeyBdInput(Structure):
>     _fields_ = [("wVk", c_ushort),
>                 ("wScan", c_ushort),
>                 ("dwFlags", c_ulong),
>                 ("time", c_ulong),
>                 ("dwExtraInfo", PUL)]
> 
> 
> class HardwareInput(Structure):
>     _fields_ = [("uMsg", c_ulong),
>                 ("wParamL", c_short),
>                 ("wParamH", c_ushort)]
> 
> 
> class MouseInput(Structure):
>     _fields_ = [("dx", c_long),
>                 ("dy", c_long),
>                 ("mouseData", c_ulong),
>                 ("dwFlags", c_ulong),
>                 ("time", c_ulong),
>                 ("dwExtraInfo", PUL)]
> 
> 
> class Input_I(Union):
>     _fields_ = [("ki", KeyBdInput),
>                 ("mi", MouseInput),
>                 ("hi", HardwareInput)]
> 
> 
> class Input(Structure):
>     _fields_ = [("type", c_ulong),
>                 ("ii", Input_I)]
> 
> 
> class POINT(Structure):
>     _fields_ = [("x", c_ulong),
>                 ("y", c_ulong)]
> 
> 
> def get_mpos():
>     orig = POINT()
>     windll.user32.GetCursorPos(byref(orig))
>     return int(orig.x), int(orig.y)
> 
> 
> def set_mpos(pos):
>     x, y = pos
>     windll.user32.SetCursorPos(x, y)
> 
> 
> MOUSEEVENTF_LEFTDOWN = 0x0002
> MOUSEEVENTF_LEFTUP = 0x0004
> 
> MOUSEEVENTF_RIGHTDOWN = 0x00008
> MOUSEEVENTF_RIGHTUP = 0x0010
> 
> 
> def move_click(pos, move_back=False):
>     origx, origy = get_mpos()
>     set_mpos(pos)
>     FInputs = Input * 2
>     extra = c_ulong(0)
>     ii_ = Input_I()
>     ii_.mi = MouseInput(0, 0, 0, 2, 0, pointer(extra))
> 
>     tt.sleep(0.1)
> 
>     ii2_ = Input_I()
>     ii2_.mi = MouseInput(0, 0, 0, 4, 0, pointer(extra))
>     x = FInputs((0, ii_), (0, ii2_))
>     windll.user32.SendInput(2, pointer(x), sizeof(x[0]))
>     if move_back:
>         set_mpos((origx, origy))
>         return origx, origy
> 
> def move_right_click(pos, move_back=False):
>     origx, origy = get_mpos()
>     set_mpos(pos)
>     FInputs = Input * 2
>     extra = c_ulong(0)
>     ii_ = Input_I()
>     ii_.mi = MouseInput(0, 0, 0, MOUSEEVENTF_RIGHTDOWN, 0, pointer(extra))
> 
>     tt.sleep(0.1)
> 
>     ii2_ = Input_I()
>     ii2_.mi = MouseInput(0, 0, 0, MOUSEEVENTF_RIGHTUP, 0, pointer(extra))
>     x = FInputs((0, ii_), (0, ii2_))
>     windll.user32.SendInput(2, pointer(x), sizeof(x[0]))
>     if move_back:
>         set_mpos((origx, origy))
>         return origx, origy
> 
> def sendkey(scancode, pressed):
>     FInputs = Input * 1
>     extra = c_ulong(0)
>     ii_ = Input_I()
>     flag = 0x8
>     ii_.ki = KeyBdInput(0, 0, flag, 0, pointer(extra))
>     InputBox = FInputs((1, ii_))
>     if scancode is None:
>         return
>     InputBox[0].ii.ki.wScan = scancode
>     InputBox[0].ii.ki.dwFlags = 0x8
> 
>     if not (pressed):
>         InputBox[0].ii.ki.dwFlags |= 0x2
> 
>     windll.user32.SendInput(1, pointer(InputBox), sizeof(InputBox[0]))
> 
> if __name__ == '__main__':
> 
>     tt.sleep(1)
>     move_click(get_mpos())
>     tt.sleep(1)
>     move_right_click(get_mpos())
> 
>     def hex_to_dec(int_hex):
>         if(isinstance(int_hex, (int, float))):
>             int_hex = str(int_hex)
>         int_dec = int(int_hex, 16)
>         return int_dec
> 
>     class ScanCode:
>         q = hex_to_dec(10)
>         w = hex_to_dec(11)
>         e = hex_to_dec(12)
>         r = hex_to_dec(13)
>         pass
>     sc = ScanCode()
> 
>     tt.sleep(1)
>     sendkey(scancode=sc.e, pressed=1)
> ```
> 
> [`键盘扫描码ScanCode参考`](https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html)
> [`鼠标参考`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput)

👍写好了整个工具类吧，用着就方便了
