### ISSUE TITLE
本地打包成exe有问题

### ISSUE THREAD

**Issue by 2a3b4c** [bode135/VirtualKey_with_Ctypes#5]
错误提示是超过最大迭代深度，然后重新设置了也没用！！

**Comment by bode135** [comment]
emmm 我明天再研究下 有阵没看了

也可以试试`keyboard`或者大漠.

**Comment by 2a3b4c** [comment]
我这边尝试更新了pyinstaller，打包成功了，但是执行没有任何效果。

**Comment by bode135** [comment]
右键管理员身份运行试试可以不



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 2a3b4c ***@***.***&gt;
发送时间: 2022年4月23日 16:20
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: bode ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [bode135/VirtualKey_with_Ctypes] 本地打包成exe有问题 (Issue #5)





 
我这边尝试更新了pyinstaller，打包成功了，但是执行没有任何效果。

**Comment by 2a3b4c** [comment]
试过了，不太行。代码需要dll的文件路径嘛

**Comment by bode135** [comment]
应该不依赖的。。。。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 2a3b4c ***@***.***&gt;
发送时间: 2022年4月23日 16:23
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: bode ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [bode135/VirtualKey_with_Ctypes] 本地打包成exe有问题 (Issue #5)





 
试过了，不太行。代码需要dll的文件路径嘛

**Comment by bode135** [comment]
解决了么

**Comment by bode135** [comment]
没解决的话我待会上班的时候偷偷看看哈哈哈

**Comment by 2a3b4c** [comment]
哈哈还没解决，现在就是用之前winio写的ps/2键盘来模拟

**Comment by bode135** [comment]
winio也太老旧了, 可以考虑keyboard. 不过我也没打包过.
或者damo, 这个我倒是常用...

**Comment by bode135** [comment]
我先研究下这个ctypes的打包

**Comment by 2a3b4c** [comment]
keyboard游戏会屏蔽

**Comment by bode135** [comment]
那没办法, 只能多备用几个驱动级按键方案..

**Comment by bode135** [comment]
大漠还是比较稳定的... 毕竟是专业做外挂的插件...

**Comment by 2a3b4c** [comment]
大漠不用收费吗哈哈

**Comment by bode135** [comment]
免费的只是不能后台按键模拟.
缺陷就是只支持32位, 得用conda管理下python环境.

**Comment by 2a3b4c** [comment]
32位倒不是啥问题，主要是能不能支持usb keyboard以及打包成exe

**Comment by bode135** [comment]
这个打包成exe倒是肯定没问题的... 我已经打包过好几次了.
另外我倒腾的这俩包都是支持usb键盘的, 毕竟我没ps/2的键盘....

**Comment by bode135** [comment]
我Ctypes打包好了 没问题呀

**Comment by bode135** [comment]
你是不是没创建新的虚拟环境...

**Comment by 2a3b4c** [comment]
创建新的虚拟环境？

**Comment by 2a3b4c** [comment]
ctype是要才32位下打包么

**Comment by bode135** [comment]
- 新建一个`main.py`

```
# main.py
from bdtime import tt  # 新版由 bd_time 改为 bdtime
from VirtualKey import keybd_event, scancode_down_up, scancodes, down_up

if __name__ == '__main__':
    string = input('请输入字符ch:')

    for s in string:
        print(f'--- 准备按下{s}字符...')
        tt.sleep(0.5)
        down_up(s)

    tt.sleep(1)
    print('运行结束.')
```
- 然后

```
pyinstaller -F main.py
```

可以发现这个是能够运行的

**Comment by bode135** [comment]
不需要32位python什么, 就正常的64位python3.6.

**Comment by 2a3b4c** [comment]
我是python3.7，打包了无法运行

**Comment by 2a3b4c** [comment]
看看你的包的版本

**Comment by bode135** [comment]
> 错误提示是超过最大迭代深度，然后重新设置了也没用！！

这个最大迭代深度... 可能是包循环引用了.
你创建一个纯净项目验证下看看.

- 我pip安装的所有版本:
```
(venv) D:\software\pycharm\myprojects\myCtypes>pip list
Package                   Version
------------------------- --------
altgraph                  0.17.2
bdtime                    0.0.7
future                    0.18.2
importlib-metadata        4.8.3
keyboard                  0.13.5
pefile                    2021.9.3
pip                       19.0.3
pyinstaller               4.10
pyinstaller-hooks-contrib 2022.0
pywin32                   303
pywin32-ctypes            0.2.0
setuptools                40.8.0
typing-extensions         4.1.1
VirtualKey                0.0.5
zipp                      3.6.0

```

**Comment by 2a3b4c** [comment]
ok，我等下试试

**Comment by 2a3b4c** [comment]
重新创建了个新的就没问题了，我怀疑python3.7以上走不通

**Comment by 2a3b4c** [comment]
打包了会被屏蔽，不打包能运行，真的搞笑
